### PR TITLE
dnstap improvements

### PR DESCRIPTION
**Pull request by edevil**
Correctly use dst ip and timestamps from response messages.
Include version and identity in messages (dnstap specific).

### CODE REVIEW

**Comment by mosajjal** [comment]
hey mate. I just looked at this, and I'm wondering if we can make up the `--serverName` string by combining Identity + Version in dnstap info, and incorporate that into the `json` outputs. So rather than having this:

``` go
type DNSResult struct {
	Timestamp    time.Time
	DNS          mkdns.Msg
	IPVersion    uint8
	SrcIP        net.IP
	DstIP        net.IP
	Protocol     string
	PacketLength uint16
	Identity     string
	Version      string
}

```
we'd have this:

```go
type DNSResult struct {
	Timestamp    time.Time
	DNS          mkdns.Msg
	IPVersion    uint8
	SrcIP        net.IP
	DstIP        net.IP
	Protocol     string
	PacketLength uint16
	ServerName     string
}
```

what do you think?

**Comment by edevil** [comment]
Hello Ali.

While I think `identity` can be used as `serverName`, it makes some sense, including `version` in it seems like a bad idea. In my case I would have to extract it again afterwards because it is something I want to store separately in order to easily compare how different versions of Unbound respond to queries.

**Comment by mosajjal** [comment]
Understood. If that's the case, let's keep serverName + version in this, and I'll work on an `interface` so we can have different fields for packets coming from `dnstap` and pcap. right now, Identity and Version are going to be two empty fields showing up on millions of packets received in live pcaps which is a major pain.

**Comment by edevil** [comment]
You mean empty fields in generated json? Which output are you using?

We can do something like https://github.com/mosajjal/dnsmonster/pull/17 to omit these fields when empty.

**Comment by mosajjal** [comment]
yep I think that works for now. thanks mate. will merge it soon

**Pull request merged**
