### PR TITLE
make use of kafka lib features

### PR DESCRIPTION
**Pull request by edevil**
This change makes it so we take advantage of kafka-go's features
such as:
 - ability to spread the messages across topic partitions
 - compression
 - internal batching
 - retries and reconnections
 - asynchronous

It also makes the code more simple and implements the close
functionality of the output.

### CODE REVIEW

**Comment by mosajjal** [comment]
hey there. Thanks for this. Have you had a chance to test this for speed? I'm keen to start writing benchmarks for these but before I do, just need to take your usage as a measure :)

**Comment by edevil** [comment]
I tested this running the whole stack on my laptop, which is not really a good benchmark. I could verify that the messages are evenly distributed across the topic partitions which was the main issue I was having.

I am also using this new patched version on a lightly loaded production unbound server, and the kafka part works correctly, but it does not have enough load to benchmark. I did find what appears to be a mem/goroutine leak in the dnstap capture code that I am going to look at.

**Comment by edevil** [comment]
https://github.com/mosajjal/dnsmonster/pull/12

**Comment by mosajjal** [comment]
cool. sounds like at least the load balancing is in place. Will merge this and possibly make it a new release so we can go test it out.

**Pull request merged**
