### PR TITLE
Rework to modern Materialized Views

### PR DESCRIPTION
**Pull request by mzealey**
- Move away from using inner MV's to separate MV and defined tables as per CH recommendations
- Switch all SummingMergeTree to AggregatingMergeTree to allow for more functionality in future if needed

### CODE REVIEW

**Comment by mosajjal** [comment]
looks good. I just tested it against some local data and it works. do you have any testing/benchmark on this? wondering if this is gonna affect the performance.

**Comment by mzealey** [comment]
There's no performance issue - it's just explicitly specifying the inner tablesOn 22 Apr 2023 08:03, Ali Mosajjal ***@***.***> wrote:
looks good. I just tested it against some local data and it works. do you have any testing/benchmark on this? wondering if this is gonna affect the performance.

**Comment by mzealey** [comment]
I've never seen a performance difference between Summing and Aggregating (with SimpleAggregationFunction), and Aggregating gives you so much more flexibility over extending function if you need.

**Comment by dnsstub** [comment]
i will post my comparisions here in 1 -2 days

**Pull request merged**
